### ISSUE TITLE
[How to?] Handle onClick in the lowest items. 

### ISSUE THREAD

**Issue by iRYO400** [zaihuishou/ExpandableRecyclerview-Databinding#2]
Hi. In first thanks for creating this library. You helped me a lot
Can you please give tips about how to handle index of clicked items in the low level and pass data then?

**Comment by zaihuishou** [comment]
Sorry so late to see your message.
You can use https://developer.android.com/topic/libraries/data-binding/index.html #Event handing to handle index of clicked items. I will update example ,Please take a look.
